#cloud-config
# Debian Trixie user-data script for CDT class
package_reboot_if_required: true
package_update: true
package_upgrade: true
ssh_pwauth: true

packages:
  - curl
  - wget
  - vim
  - openssh-server
  - tmux
  - nano
  - screen
  - magic-wormhole
  - net-tools
  - htop
  - xrdp
  - git

# Run commands after boot
runcmd:
  - systemctl enable --now xrdp
  - systemctl enable --now ssh
  - echo "CDT Debian VM setup completed" >> /var/log/cdt-setup.log
  - date >> /var/log/cdt-setup.log

# Set timezone
timezone: America/New_York

# Create a simple motd
final_message: "CDT Debian Trixie VM is ready for class!"
